DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
    PRODUCT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_CORP VARCHAR(255),
    PRODUCT_NORMALIZED_NAME VARCHAR(255) UNIQUE,
    NUTRITION_FACTS JSON,
    MEMBER_ID BIGINT,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);
