spring:
  application:
    name: nutridiary
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/nutridiary
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver