spring:
  application:
    name: nutridiary
  datasource:
    url: jdbc:mysql://localhost:3306/nutridiary
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: optional:classpath:db/data.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: debug